#### Решите линейное уравнение с матричными неизвестным X и параметрами. ####

$ AX+B=C$

$B = \begin{bmatrix}
 1.2\\
 3.3\\
5.1
\end{bmatrix}$  $C = \begin{bmatrix}
 3.2\\
 4.5\\0.3
\end{bmatrix}$  $A = \begin{bmatrix}
0.1 & 2.1 & 4.1 \\
3.2 & 1.8 & 2.6 \\
1.1 & 6.2 & 3.4 \\
\end{bmatrix}$

In [57]:
from sympy import Matrix, linsolve

# Определите матрицы A, B и C
A = Matrix([
    [0.1, 2.1, 4.1],
    [3.2, 1.8, 2.6],
    [1.1, 6.2, 3.4]
])

B = Matrix([1.2, 3.3, 5.1])
C = Matrix([3.2, 4.5, 0.3])

# Вычислите C - B
C_minus_B = C - B

In [58]:
# Решите уравнение AX = C - B
X = linsolve((A, C_minus_B))
X

{(0.201357792864365, -1.49451105012278, 1.24837498194424)}

In [59]:
# Преобразуем результат в численное представление
X_evalf = [x.evalf() for x in X.args[0]]
X_evalf

[0.201357792864365, -1.49451105012278, 1.24837498194424]

In [60]:
print("Решение X:")
print(Matrix(X_evalf))

Решение X:
Matrix([[0.201357792864365], [-1.49451105012278], [1.24837498194424]])


In [61]:
AX = A * Matrix(X_evalf)
print("Проверка: AX + B =", AX + B)
print("C =", C)

Проверка: AX + B = Matrix([[3.20000000000000], [4.50000000000000], [0.300000000000000]])
C = Matrix([[3.20000000000000], [4.50000000000000], [0.300000000000000]])


Вторая система линейных уравнений
$B = \begin{bmatrix}
9 & 5 & 2 \\
4 & 7 & 7 \\
4 & 7 & 2 \\
\end{bmatrix}$  $C = \begin{bmatrix}
5 & 3 & 7 \\
8 & 9 & 9 \\
3 & 1 & 7 \\
\end{bmatrix}$  $A = \begin{bmatrix}
8 & 9 & 2 \\
8 & 2 & 5 \\
1 & 9 & 3.4 \\
\end{bmatrix}$

In [62]:
import numpy as np

# Матрица A
A = np.array([
    [8, 9, 2],
    [8, 2, 5],
    [1, 9, 6]
])

# Матрицы B и C
B = np.array([
    [9, 5, 2],
    [4, 7, 7],
    [4, 7, 2]
])

C = np.array([
    [5, 3, 7],
    [8, 9, 9],
    [3, 1, 7]
])

# Вычисляем правую часть: C - B
C_minus_B = C - B

# Проверяем обратимость матрицы A
try:
    A_inv = np.linalg.inv(A)  # Обратная матрица A
except np.linalg.LinAlgError:
    print("Матрица A вырожденная (определитель равен нулю), решение не существует")
else:
    # Решаем уравнение AX = D
    X = A_inv @ C_minus_B
    print("Решение X:")
    print(X)

    # Проверка: AX + B ≈ C
    AX_plus_B = A @ X + B
    print("\nПроверка: AX + B ≈ C")
    print(AX_plus_B)

Решение X:
[[ 0.1037182   0.49315068  0.06262231]
 [-0.74363992 -0.63013699  0.47553816]
 [ 0.93150685 -0.1369863   0.10958904]]

Проверка: AX + B ≈ C
[[5. 3. 7.]
 [8. 9. 9.]
 [3. 1. 7.]]
